server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/charvaq
    username: postgres
    password: 123

    main:
      allow-bean-definition-overriding: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
#spring.main.lazy-initialization=true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

jwt:
  token:
    secret: jwtcleeancode
    validity: 8640000

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    tryItOutEnabled: true
    path: swagger-ui
    csrf:
      enabled: true
